### ISSUE TITLE
Swarmie doesn't build in rust 1.87.0

### ISSUE THREAD

**Issue by Mark1626** [n0-computer/swarmie#6]
I get the following error when running `cargo build`

```
error[E0282]: type annotations needed for `Box<_>`
  --> /path/to/rust/1.87.0/registry/src/index.crates.io-1949cf8c6b5b557f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`

   Compiling xmltree v0.10.3
   Compiling enumflags2 v0.7.9
   Compiling hyper v0.14.28
   Compiling quinn v0.10.2
   Compiling hmac-sha1 v0.2.2
   Compiling hyper-util v0.1.3
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

I did a `cargo update` and tried a rebuild and got this instead, which I think is an upstream issue with `iroh-pkarr-node-discovery` needing `pkarr` version `1.1.5`

```
error[E0432]: unresolved imports `mainline::DhtSettings`, `mainline::GetMutableResponse`, `mainline::MutableItem`, `mainline::Response`, `mainline::StoreQueryMetdata`
 --> /path/to/rust/1.87.0/registry/src/index.crates.io-1949cf8c6b5b557f/pkarr-1.1.5/src/lib.rs:4:21
  |
4 | use mainline::{Dht, DhtSettings, GetMutableResponse, MutableItem, Response, StoreQueryMetdata};
  |                     ^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^  ^^^^^^^^^^^^^^^^^ no `StoreQueryMetdata` in the root
  |                     |            |                   |            |
  |                     |            |                   |            no `Response` in the root
  |                     |            |                   no `MutableItem` in the root
  |                     |            no `GetMutableResponse` in the root
  |                     no `DhtSettings` in the root
  |
  = help: consider importing this struct instead:
          mainline::dht::DhtSettings
  = help: consider importing this struct instead:
          mainline::common::GetMutableResponse
  = help: consider importing this struct instead:
          mainline::common::MutableItem
  = help: consider importing this struct instead:
          mainline::common::Response
  = help: consider importing this struct instead:
          mainline::common::StoreQueryMetdata

For more information about this error, try `rustc --explain E0432`.
error: could not compile `pkarr` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

```

Seems to be related to #5
